Join infinispan scenarios in order to reduce native package time
quarkus-qe/beefy-scenarios pull request #152
Opened 2021-03-22 15:46 UTC by pjgg

2021-03-22 16:03 UTC, rsvoboda commented
Adding Kyrylo as he worked on 008 module. 

Maybe the 009 module name could be adjusted to mention `SSL/TLS` addition in https://github.com/quarkus-qe/beefy-scenarios/commit/042a7a9f8c6513ffe489a96bbb469ef7b515afe9

2021-03-23 15:48 UTC, kshpak requested changes
Please also migrate README from the removed module and add a note that it is covered inside quickstart package

2021-03-23 15:48 UTC, kshpak commented on 009-quarkus-infinispan-grpc-kafka/src/main/resources/application.properties
> +#quarkus.infinispan-client.sasl-mechanism=DIGEST-MD5
I like the comment, but IMO it's redundant to leave props here.
Comment can state that: Infinispan client credentials are picked at build time from hotrod-client.properties

2021-03-23 15:48 UTC, kshpak commented on 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/quickstart/InfinispanServerResourceTest.java
> +
Delete extra line

2021-03-23 15:48 UTC, kshpak commented on 009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/containers/InfinispanTestResource.java
> +                .withEnv("PASS", "my_password")
These props are taken from identities.yaml file. Delete these two lines

2021-03-24 10:40 UTC, pjgg commented
> Adding Kyrylo as he worked on 008 module.
> 
> Maybe the 009 module name could be adjusted to mention `SSL/TLS` addition in [042a7a9](https://github.com/quarkus-qe/beefy-scenarios/commit/042a7a9f8c6513ffe489a96bbb469ef7b515afe9)

Added on the Readme

2021-03-24 13:04 UTC, rsvoboda commented
rebase pls

2021-03-24 15:38 UTC, rsvoboda commented
@kshpak, is the PR OK from your side?

2021-03-24 16:31 UTC, kshpak commented
> @kshpak, is the PR OK from your side?

Approve from my side

2021-03-24 16:32 UTC, kshpak approved these changes

2021-03-24 16:44 UTC, rsvoboda commented
008 .. there is just readme with pointer to the new location

2021-03-24 16:44 UTC, rsvoboda commented
I will wait for CI before approving

2021-03-25 07:04 UTC, rsvoboda approved these changes

2021-03-25 07:05 UTC, merged