Configure Github CI to run tests on Windows
quarkus-qe/beefy-scenarios pull request #202
Opened 2021-05-06 12:39 UTC by Sgitario

Configured only for:
- PRs (similarly as done for Linux)
- Daily (only graalvm)

Not done for Ecosystem.

2021-05-07 07:16 UTC, Sgitario commented
Daily run example in https://github.com/Sgitario/beefy-scenarios/actions/runs/819135711

2021-05-16 20:04 UTC, mjurc requested changes
Besides the two nitpicks, LGTM

2021-05-16 20:04 UTC, mjurc commented on .github/workflows/daily.yaml
> +          mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify
Repeated `-fae`

2021-05-16 20:04 UTC, mjurc commented on .github/workflows/daily.yaml
> +          mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify -Dnative \
Again, duplication of `-fae`

2021-05-17 05:14 UTC, Sgitario commented on .github/workflows/daily.yaml
> +          mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify
Fixed

2021-05-17 05:14 UTC, Sgitario commented on .github/workflows/daily.yaml
> +          mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify -Dnative \
Fixed

2021-05-19 05:18 UTC, Sgitario commented
@mjurc would you mind to take a look into this PR? Thanks in advance,

2021-05-19 08:28 UTC, mjurc commented
Looks good to me, merging!

2021-05-19 08:28 UTC, merged