Conflicts between reactive and non-reactive libraries
quarkus-qe/beefy-scenarios pull request #254
Opened 2021-09-21 09:17 UTC by pjgg

2021-09-21 11:56 UTC, rsvoboda commented on 002-quarkus-all-extensions/src/main/resources/application.properties
> +quarkus.devservices.enabled=false
already there, two lines above :)

2021-09-21 11:57 UTC, rsvoboda requested changes
just small change needed

2021-09-22 08:06 UTC, pjgg commented
The native error is because `002-quarkus-all-extensions` module is not included in the native profile.

2021-09-22 08:10 UTC, rsvoboda approved these changes

2021-09-22 08:11 UTC, merged