Migrate Bitnami images to the official ones
quarkus-qe/beefy-scenarios pull request #277
Opened 2022-04-21 22:11 UTC by michalvavrik

Today [Bitnami migrated](https://github.com/bitnami-labs/sealed-secrets/issues/822#issuecomment-1104116084) their images to [Dockerhub Bitnami](https://hub.docker.com/u/bitnami). The migration caused several test errors in [beefy-scenarios](https://github.com/quarkus-qe/beefy-scenarios), more specifically:

- `014-quarkus-panache-with-transactions-xa` failed due to missing `quay.io/bitnami/mysql:5.7.32`
- `019-quarkus-consul` failed due to missing `quay.io/bitnami/consul:1.9.3`
- `302-quarkus-vertx-jwt` failed due to missing `quay.io/bitnami/redis:6.0`
- `002-quarkus-all-extensions` failed due to missing `quay.io/bitnami/mongodb:4.0.23`

while I didn't find connect between migration and following failures (so far, there might be correlation between `302-quarkus-vertx-jwt` and other `vertx` failures): 

- `013-quarkus-oidc-restclient`
- `300-quarkus-vertx-webclient`
- `301-quarkus-vertx-kafka`

This PR migrates Bitnami images to the official ones:
quay.io/bitnami/mongodb:4.0.23 ----> mongo:4.0.23
quay.io/bitnami/mysql:5.7.32 -------> mysql:5.7 (change suggested here)[https://github.com/quarkus-qe/quarkus-test-suite/pull/608#discussion_r855145711]
quay.io/bitnami/postgresql:13.4.0 ----> postgres:13.6 (mirroring changes made here)[https://github.com/quarkus-qe/quarkus-test-suite/pull/608/files]
quay.io/bitnami/mysql:8.0 ----->   mysql:8.0
quay.io/bitnami/consul:1.9.3 ----> 1.9.3
quay.io/bitnami/redis:6.0 ----> redis:6.0

2022-04-22 07:20 UTC, pjgg commented
please review CI failures!

2022-04-22 07:27 UTC, rsvoboda requested changes
Please use long names with `docker.io/` prefix

e.g. `docker.io/consul:1.9.3`

2022-04-22 08:19 UTC, rsvoboda commented
`013-quarkus-oidc-restclient` fails because of recent change in Quarkus main - https://github.com/quarkusio/quarkus/pull/24666

Test needs to be adjusted to check for enhanced details

2022-04-22 10:49 UTC, michalvavrik commented
PR now uses long docker image names (please see a separate commit).

`013-quarkus-oidc-restclient` test is fixed by setting a same OpenApi Info title for both JVM and Native build ([previously we counted on different behavior between two modes](https://github.com/quarkus-qe/beefy-scenarios/pull/244/files), which didn't work in our Pull Requirest Build pipeline)

2022-04-22 12:01 UTC, rsvoboda commented
ah, so you are dsiabling the tests in 300 and 301

I have prepare https://github.com/quarkus-qe/beefy-scenarios/pull/278 to fix those modules

So maybe the best way would be to cherry-pick my commit and use it in this PR

2022-04-22 12:42 UTC, michalvavrik commented
I review your PR and looks good, therefore I got rid of the commit that disabled tests. thanks!

2022-04-22 15:55 UTC, rsvoboda commented
To fix 303 and 304 you need to add these changes:

**303-quarkus-vertx-sql**
```diff
--- a/303-quarkus-vertx-sql/pom.xml
+++ b/303-quarkus-vertx-sql/pom.xml
@@ -44,6 +44,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-flyway</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.flywaydb</groupId>
+            <artifactId>flyway-mysql</artifactId>
+        </dependency>
         <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-smallrye-openapi</artifactId>
```
Details in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7#flyway

**304-quarkus-vertx-routes**
```diff
diff --git a/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationAssertions.java b/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationAssertions.java
index 1bef9e6..2dcbed6 100644
--- a/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationAssertions.java
+++ b/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationAssertions.java
@@ -17,7 +17,7 @@ public class ValidationAssertions {
     }

     public static final void assertValidationErrorDetails(ValidationErrorResponse response) {
-        assertEquals("validation constraint violations", response.getDetails());
+        assertEquals("validation constraint violations", response.getDetail());
     }

     public static final void assertValidationErrorStatus(ValidationErrorResponse response, int expected) {
diff --git a/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationErrorResponse.java b/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationErrorResponse.java
index 2d7ef42..86c8d38 100644
--- a/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationErrorResponse.java
+++ b/304-quarkus-vertx-routes/src/test/java/io/quarkus/qe/validation/utils/ValidationErrorResponse.java
@@ -2,7 +2,7 @@ package io.quarkus.qe.validation.utils;

 public class ValidationErrorResponse {
     private String title;
-    private String details;
+    private String detail;
     private int status;
     private ValidationError[] violations;

@@ -14,12 +14,12 @@ public class ValidationErrorResponse {
         this.title = title;
     }

-    public String getDetails() {
-        return details;
+    public String getDetail() {
+        return detail;
     }

-    public void setDetails(String details) {
-        this.details = details;
+    public void setDetail(String details) {
+        this.detail = details;
     }

     public int getStatus() {
```

Response changed (was fixed, details => detail), example:
```json
{
    "title": "Constraint Violation",
    "detail": "validation constraint violations",
    "status": 400,
    "violations": [
        {
            "field": "validateRequestBody.param.custom",
            "message": "Value must be uppercase"
        }
    ]
}
```

2022-04-22 19:30 UTC, rsvoboda commented
Vanilla MySQL needs more specific log entry check, it prints log with `ready for connections` in the DB setup phase.  Bitnami has different logs in DB setup phase. 

 - `docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw  mysql:8.0`
 - `docker run --name some-mysql-bit -e MYSQL_ROOT_PASSWORD=my-secret-pw quay.io/bitnami/mysql:8.0`

2022-04-22 19:49 UTC, michalvavrik commented
@rsvoboda thank you, I've tried that moments before with ".*/usr/sbin/mysqld: ready for connections.*" which didn't fix, but your log message works.

2022-04-23 18:38 UTC, michalvavrik commented
Build currently fails on 301-quarkus-vertx-kafka#ConfluentKafkaTest, I think the problem was introduced with [this commit on Friday](https://github.com/quarkusio/quarkus/pull/24526), but it's not related to this PR, so maybe we could merge this commit and resolve the problem in a separate issue? Thank you

2022-04-25 07:06 UTC, rsvoboda approved these changes

2022-04-25 07:07 UTC, merged

2022-04-25 07:13 UTC, rsvoboda commented
Please continue with `301-quarkus-vertx-kafka#ConfluentKafkaTest` in separate PR