Infinispan gRPC Kafka: Add mutiny gRPC service
quarkus-qe/beefy-scenarios pull request #53
Opened 2020-12-03 07:21 UTC by Sgitario

gRPC supports both blocking and non-blocking (mutiny) approaches. We had implemented only the blocking scenario. In this PR, we're covering the non-blocking one.

2020-12-14 12:19 UTC, rsvoboda commented
Set @pjgg as reviewer for this PR, he is looking at grpc / http2 atm, he should review this PR.

2020-12-14 12:19 UTC, rsvoboda approved these changes

2020-12-14 14:00 UTC, pjgg requested changes

2020-12-14 14:14 UTC, Sgitario commented on 009-quarkus-infinispan-grpc-kafka/src/main/java/io/quarkus/qe/greeting/GreetingResource.java
> +                .await().atMost(Duration.ofSeconds(1)).getMessage();
The intention is to use the inner mutiny client, not to return a non-blocking message.

2020-12-24 10:20 UTC, pjgg approved these changes

2020-12-24 10:27 UTC, merged