Spring beans and JPA test coverage
quarkus-qe/beefy-scenarios pull request #62
Opened 2020-12-22 17:16 UTC by pjgg

Issues References:
-----------------------------
[Fix spring-data-jpa field lookup with layered @MappedSuperclasses](https://issues.redhat.com/browse/QUARKUS-532)
[Make embedded fields with camel-case work in Spring Data JPA repositories](https://issues.redhat.com/browse/QUARKUS-525)
[Spring's @Scope#scopeName is now taken into account](https://issues.redhat.com/browse/QUARKUS-547)

### Fix spring-data-jpa field lookup with layered @MappedSuperclasses

We have added a "super" structure over the existing Cat entity. With the current implementation Cats extends Mammal and mammal are animal.

### Make embedded fields with camel-case work in Spring Data JPA repositories

We've created a query over an existing camelCase field.

### Spring's @Scope#scopeName is now taken into account

We've created an HTTP Request filter in order to add headers to the response:

- x-session: Keep the same value per Http session
- x-count: count the number of requests
- x-request: increase his value per request
- x-instance: represents the instance ID. Must be unique per pod. 
-

2020-12-23 07:29 UTC, rsvoboda requested changes
Running with 1.7.6.Final makes the tests pass.

Running with 1.7.5.Final makes some tests fail, but only tests related to the scope, not the tests for 2 additional issues.

```
[INFO]
[ERROR] Failures:
[ERROR]   CommonsHeadersTest.testRequestAmount:30
Expected: is <3>
     but: was <1>
[ERROR]   CommonsHeadersTest.testRequestScope:52
Expected: is <3>
     but: was <1>
[ERROR] Errors:
[ERROR]   CommonsHeadersTest.testSessionScope:60 » IllegalArgument Session id value cann...
[INFO]
[ERROR] Tests run: 12, Failures: 2, Errors: 1, Skipped: 0
```

Improve the log messages, it's not clear what went wrong when looking into test results.
People would need to open the code and investigate from there, that's quite time consuming and some people can have hard time understanding all the parts of the code. 

Also please add README.md into the 601 module and copy there text from description of this PR.

2020-12-23 07:29 UTC, rsvoboda commented on 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/CatResource.java
> +import javax.ws.rs.*;
Please use individual imports, IDE can be hinted to avoid star imports by increasing the default (usually 5) number of imports before doing .*

2020-12-23 07:29 UTC, rsvoboda commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java
> +    void testfindCatsByDeathReason() {
```suggestion
    void testFindCatsByDeathReason() {
```

2020-12-23 07:29 UTC, rsvoboda commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/BookResourceTest.java
> +    @Test
Add comment that mentions QUARKUS-525

2020-12-23 07:29 UTC, rsvoboda commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CatResourceTest.java
> +    @Test
Add comment that mentions https://issues.redhat.com/browse/QUARKUS-532

2020-12-23 07:29 UTC, rsvoboda commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
> +public class CommonsHeadersTest {
Add comment that mentions https://issues.redhat.com/browse/QUARKUS-547

2020-12-23 09:27 UTC, pjgg commented
CodeReview improvements
------------------------------------
- Improve test error messages
- Remove some unused imports and disable * imports
- Add Readme
- Add comment to some test in order to point to the related issue number.
- Some other cosmetic changes

2020-12-23 11:42 UTC, rsvoboda approved these changes

2020-12-23 11:55 UTC, Sgitario requested changes
Some minor comments

2020-12-23 11:55 UTC, Sgitario commented on 601-spring-data-primitive-types/src/main/java/io/quarkus/qe/spring/data/model/Animal.java
> +    public String getDeathReason() {
Do we need the getter methods? I tried with getters and without, and the test passes.
Also, take into account that the rest of entities define the fields as private fields and then the getter and the setter methods.

2020-12-23 11:55 UTC, Sgitario commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
> +            xCount.addAll(new HashSet<>(headers.getValues("x-count")));
Why not adding the collection to the set directly? xCount.addAll(headers.getValues...)

2020-12-23 11:55 UTC, Sgitario commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
> +            instanceIds.addAll(new HashSet<>(headers.getValues("x-instance")));
Why not adding the collection to the set directly? instanceIds.addAll(headers.getValues...)

2020-12-23 11:55 UTC, Sgitario commented on 601-spring-data-primitive-types/src/test/java/io/quarkus/qe/spring/data/CommonsHeadersTest.java
> +            requestIds.addAll(new HashSet<>(headers.getValues("x-request")));
Why not adding the collection to the set directly? requestIds.addAll(headers.getValues...)

2020-12-23 13:04 UTC, rsvoboda commented
Just one reminder, once this gets into master, please prepare PR for 1.7 branch.

2021-01-04 11:23 UTC, rsvoboda commented
Jose is on PTO, merging. If something needs additional work, it can be done in follow-up PR.
@pjgg please prepare PR for 1.7 branch

2021-01-04 11:23 UTC, merged