Check quarkus.smallrye-openapi.store-schema-directory property and http Client improve coverage
quarkus-qe/beefy-scenarios pull request #79
Opened 2021-01-27 16:31 UTC by pjgg

OpenAPI and httpClient coverage

- Cover Open API store-schema-directory property.

- add some extra tests that cover GET/POTS/PUT/DELETE HTTP methods over sync/async(Mutiny) Rest API(Server and client-side).

2021-01-28 08:16 UTC, rsvoboda requested changes

2021-01-28 08:16 UTC, rsvoboda commented on 013-quarkus-oidc-restclient/pom.xml
> +<!--  Looks that it's not required, however Docs says the opposite. https://quarkus.io/guides/rest-client#async-support        -->
I think it is thanks to `quarkus-resteasy-mutiny` dependency on line 17 + `quarkus-rest-client` on line 29.

the missing part is probably just `extensions/rest-client-mutiny/deployment/src/main/java/io/quarkus/restclient/mutiny/deployment/RestClientMutinyProcessor.java`

I think `quarkus-rest-client` could be removed and `quarkus-rest-client-mutiny` enabled to be safe for the future (if rest-client-mutiny gets enhanced)

2021-01-28 08:16 UTC, rsvoboda commented on 013-quarkus-oidc-restclient/pom.xml
> +<!--  Looks that it's not required, however Docs says the opposite. https://quarkus.io/guides/rest-client#async-support        -->
https://mvnrepository.com/artifact/io.quarkus/quarkus-rest-client-mutiny/1.11.0.Final

2021-01-28 08:19 UTC, Sgitario requested changes

2021-01-28 08:19 UTC, Sgitario commented on 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/OpenApiTest.java
> +public class OpenApiTest {
Apart from the @rsvoboda 's comments, I'm missing the Native version of this test.

2021-01-28 12:31 UTC, rsvoboda commented on 013-quarkus-oidc-restclient/src/test/java/io/quarkus/qe/OpenApiTest.java
> +}
Please add test for content of generated json / yaml files.

2021-01-29 06:03 UTC, Sgitario approved these changes

2021-01-29 12:05 UTC, rsvoboda approved these changes

2021-01-29 12:06 UTC, merged