RESTEasy multipart scenario - enhanced version
quarkus-qe/beefy-scenarios pull request #89
Opened 2021-02-12 21:33 UTC by rsvoboda

RESTEasy multipart scenario

2021-02-12 21:39 UTC, rsvoboda commented
@jsmrcka please take a look, based on your work, but the finalization polish ++ usage of `byte[]` for image/data part makes it easier to understand

2021-02-16 16:14 UTC, kshpak commented
@rsvoboda I would prefer to go with a dedicated module for the multipart scenario.

2021-02-16 16:19 UTC, jsmrcka commented on 001-quarkus-getting-started/src/test/java/io/quarkus/qe/core/AsciiMultipartResourceTest.java
> +    public static final byte[] EXPECTED_ASCII_BYTES = {80, -17, -65, -67, -17, -65, -67, 105, 107, 114, -17, -65, -67, -17, -65, -67, -17, -65, -67, -17, -65, -67, 108, 101, 110, -17, -65, -67, -17,
Couldn't we do something like this:
```
private static final String EXPECTED_ASCII_TEXT = new String(TEXT_WITH_DIACRITICS.getBytes(StandardCharsets.UTF_8), StandardCharsets.US_ASCII);
```
and later test for:
```
...
.body(not(equalTo(TEXT_WITH_DIACRITICS)))
.body(equalTo(EXPECTED_ASCII_TEXT));
```

2021-02-17 07:21 UTC, rsvoboda commented
PR updated, comments reflected.

2021-02-17 07:48 UTC, kshpak commented on 001-quarkus-getting-started-with-jaxrs/pom.xml
> +    <dependency>
Adjust please <artifactId> to _001-quarkus-getting-started-with-jaxrs_

2021-02-17 07:51 UTC, kshpak requested changes
Adjust please **artifactId** to _001-quarkus-getting-started-with-jaxrs_ in module's pom.xml

2021-02-17 09:25 UTC, rsvoboda commented
@kshpak PR updated, thanks for noticing

2021-02-17 09:37 UTC, kshpak approved these changes

2021-02-17 09:38 UTC, jsmrcka approved these changes

2021-02-17 10:07 UTC, merged