Add basic consul scenario
quarkus-qe/beefy-scenarios pull request #94
Opened 2021-02-16 13:42 UTC by Sgitario

Module that covers the integration with Consul and ensure that changes in consul will take effect in the application.
Concretely, this module implements a resource that returns `Hello {some.property}`. By default, `some.property` is `Default`. If we change this property in consul and reload the application, we verify that the new property is taken from consul.

2021-02-18 23:30 UTC, mjurc approved these changes
LGTM.

2021-02-19 07:53 UTC, rsvoboda commented
@kshpak, please take a look, waits for your review now

2021-02-19 08:54 UTC, kshpak requested changes
It's failing for me:
```
reetingResourceTest.java:[62,12] cannot find symbol
  symbol:   method start()
  location: variable app of type io.quarkus.test.QuarkusProdModeTest
```
the same with method stop()

2021-02-19 08:58 UTC, Sgitario commented
> It's failing for me:
> 
> ```
> reetingResourceTest.java:[62,12] cannot find symbol
>   symbol:   method start()
>   location: variable app of type io.quarkus.test.QuarkusProdModeTest
> ```
> 
> the same with method stop()

You need to run this module with the latest changes in Quarkus upstream. (Make sure you have fetched the changes from upstream into your fork).

2021-02-19 09:21 UTC, kshpak commented
@Sgitario I simply forget to fetch, you're right. Didn't get my coffee yet :D sry

2021-02-19 09:25 UTC, kshpak approved these changes

2021-02-19 10:28 UTC, rsvoboda commented
@kshpak please merge, you should have right for it

2021-02-19 10:50 UTC, merged

2021-02-25 14:25 UTC, rsvoboda commented on 019-quarkus-consul/src/test/java/io/quarkus/qe/containers/ConsulTestResource.java
> +                .withNetworkMode("host")
This won't work on Windows a macOS!